# Generated by Django 4.2.2 on 2023-07-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
